### ISSUE TITLE
connect problem

### ISSUE THREAD

**Issue by trevery** [mikevanis/SugruBot#1]
Hi Mikevanis， SugruBot is funny in your video. So I remixed one using the servo mg996r, which i often use in my project. But i meet some problem following your instructables.
---

- which servo pin is seg0?
    When I use  Processing to control my SugruBot, sugrubot seems like crazy and didn't look like the sketch in Processing.So I think seg0,1,2 may not map pin 8,9,10.

**Comment by mikevanis** [comment]
Hi Trevery! Thanks for remixing and building the robot! So cool! This GitHub repository is outdated. Try to use [this repository](https://github.com/mikevanis/Fixbot) instead. Pins 8-12 are used for each segment. 8 is the first servo closer to the base. Send me a picture if you can, I'd love to see it!
